### ISSUE TITLE
App continuos shows "Device sync complete" and nothing happens

### ISSUE THREAD

**Issue by danielbernalb** [kike-canaries/canairio_android#71]
**Describe the bug**
App continuos shows "Device sync complete" and nothing happens

**To Reproduce**
The Setting option 

Version of the app 0.3.2

![Uno](https://user-images.githubusercontent.com/42117424/106019370-94075e00-6090-11eb-940d-34d63c828229.gif)

**Comment by hpsaturn** [comment]
resolved in #78
